"""empty message

Revision ID: c373eadefe59
Revises: 610c4f7d2e7f
Create Date: 2024-07-02 14:07:31.929156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c373eadefe59'
down_revision = '610c4f7d2e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_name', sa.String(length=128), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=False))
        batch_op.drop_column('adress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adress', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('address')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('city_name')

    # ### end Alembic commands ###
